/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Antique_chair_2.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Antique_chair_2.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes['1_001_low003_1'].geometry} material={materials.antique_chair_01} position={[0, 0, 2.043]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['1_006_low003_1'].geometry} material={materials.antique_chair_01} position={[0, 0, 2.043]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['1_015_low003_1'].geometry} material={materials.antique_chair_01} position={[0, 102.581, -22.692]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['1_002_low003_1'].geometry} material={materials.antique_chair_01} position={[0, 46.679, 24.148]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['1_003_low003_1'].geometry} material={materials.antique_chair_01} position={[0, 48.802, -20.11]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['1_005_low003_1'].geometry} material={materials.antique_chair_01} position={[0, 5.135, 2.292]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['1_007_low007_1'].geometry} material={materials.antique_chair_01} position={[0, 46.679, 24.148]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['1_008_low003_1'].geometry} material={materials.antique_chair_01} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['1_009_low003_1'].geometry} material={materials.antique_chair_01} position={[0, 95.359, -22.307]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['1_010_low003_1'].geometry} material={materials.antique_chair_01} position={[0, 77.533, -21.029]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['1_013_low003_1'].geometry} material={materials.antique_chair_01} position={[0, 115.575, -24.035]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['1_016_low003_1'].geometry} material={materials.antique_chair_01} position={[0, 48.802, 8.259]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['1_007_low008_1'].geometry} material={materials.antique_chair_01} position={[0, 46.679, 24.148]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes['1_004_low003_1'].geometry} material={materials.antique_chair_01} position={[0, 46.679, 2.047]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/Antique_chair_2.gltf')
